### ISSUE TITLE
custom songs?

### ISSUE THREAD

**Issue by REAPXR666** [Abhijeet-Pitumbur/Hyperdrive#1]
how do i add my own music to the game?
would help alot!

**Comment by Abhijeet-Pitumbur** [comment]
You can add music of your choice by opening the project in Unity: 
1. Import the audio clips into 'Project > Assets > Sounds > Music'. 
2. In the Inspector window of 'Music.cs' file in 'Project > Assets > Scripts', drag and drop the audio clips into the array of songs. 
3. Build the game. 
(Sorry for the very late reply)
